# Generated by Django 3.2.1 on 2021-05-15 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agat', '0005_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
    ]
