# Generated by Django 3.2.1 on 2021-05-15 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agat', '0007_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
    ]
