# Generated by Django 3.2.1 on 2021-05-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agat', '0008_remove_subcategory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_name', models.CharField(blank=True, max_length=50, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Вступление')),
                ('slug', models.SlugField(max_length=70, unique=True)),
            ],
            options={
                'verbose_name': 'вступление (имена)',
                'verbose_name_plural': 'вступление (имена)',
            },
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
