# Generated by Django 3.2.1 on 2021-05-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agat', '0012_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prefix',
            field=models.CharField(blank=True, max_length=30, verbose_name='Префикс'),
        ),
    ]
