# Generated by Django 3.2.1 on 2021-05-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agat', '0013_product_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_code',
            field=models.CharField(blank=True, max_length=30, verbose_name='Код флатикона'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=70, verbose_name='Описание для Главной'),
        ),
    ]
