# Generated by Django 3.2.1 on 2021-05-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agat', '0016_auto_20210518_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='subtitle',
            field=models.CharField(blank=True, max_length=70, verbose_name='Название'),
        ),
    ]
