# Generated by Django 3.2.1 on 2021-05-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agat', '0018_auto_20210519_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Флатикон'),
        ),
    ]
