# Generated by Django 3.2.1 on 2021-05-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agat', '0019_service_icon_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Название в шапке')),
                ('subtitle', models.CharField(blank=True, max_length=70, verbose_name='Подзаголовок перед текстом')),
                ('text', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(max_length=70, unique=True)),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'О компании',
                'verbose_name_plural': 'О компании',
            },
        ),
    ]
