# Generated by Django 3.2.1 on 2021-05-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agat', '0021_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price_item',
            field=models.CharField(blank=True, max_length=200, verbose_name='Текстовый пункт прайса'),
        ),
        migrations.AlterField(
            model_name='price',
            name='subtitle',
            field=models.CharField(blank=True, max_length=70, verbose_name='Подраздел'),
        ),
        migrations.AlterField(
            model_name='price',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название раздела'),
        ),
    ]
