# Generated by Django 3.2.1 on 2021-05-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agat', '0023_alter_price_price_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='price_content',
            field=models.TextField(blank=True, verbose_name='Описание тарифа'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_item',
            field=models.CharField(blank=True, max_length=30, verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='price',
            name='subtitle',
            field=models.CharField(blank=True, max_length=30, verbose_name='Подраздел'),
        ),
    ]
