# Generated by Django 3.2.1 on 2021-05-20 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agat', '0027_thanks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thanks',
        ),
    ]
