# Generated by Django 3.2.1 on 2021-05-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agat', '0028_delete_thanks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=70, verbose_name='Название'),
        ),
    ]
