# Generated by Django 3.2.1 on 2021-05-24 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agat', '0032_feedbackphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackphone',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата'),
        ),
    ]
